# Whether messages will be translated into each player's locale.
# Commands run from the console will be translated into the host's locale.
# If false, all messages will be translated into the default locale.
per-user-translations: true
# The default locale/language of the plugin.
# If per-user-translations is false or the user does not have a supported locale, this locale will be used.
# A list of locales is at https://www.localeplanet.com/java/
default-locale: "en"
