name: NameHistorian
version: '${version}'
description: "Records and looks up player name history"
main: com.tisawesomeness.namehistorian.spigot.NameHistorianSpigot
api-version: 1.19
authors: [ Tis_awesomeness ]
commands:
  history:
    description: "Look up a player's name history"
    aliases: [ hist, namehist, namehistory ]
    permission: namehistorian.history
    permission-message: "§cYou do not have permission to use this command."
permissions:
  namehistory.*:
    default: op
    children:
      namehistory.history: true
  namehistory.history:
    description: "Allows using the /history command"
    default: op
